# ROUTING PARA SISTEMA DE LOGIN ADMINISTRADOR
loginAdmin:
    path: /loginAdmin
    defaults: { _controller: AppBundle:Admin:loginAdmin }
# ROUTING PARA SISTEMA DE LOGIN ADMINISTRADOR
login:
    path: /login
    defaults: { _controller: AppBundle:Login:login }

login_check:
    path: /login_check

logout:
    path: /logout
#-------------------------------------------------------------#
# ROUTING PARA PERFIL DE ADMIN
perfil_admin:
    path: /perfil_admin
    defaults: { _controller: AppBundle:Admin:perfil }
#-------------------------------------------------------------#
# ROUTING PARA INDEX DE ADMIN
index:
    path: /index
    defaults: { _controller: AppBundle:Admin:index }
# ROUTING PARA CONTROL DE ACCESO
acceso:
    path: /acceso
    defaults: { _controller: AppBundle:Admin:acceso }
# ROUTING PARA CONTROL DE ANTIGUEDAD
antiguedad:
    path: /antiguedad
    defaults: { _controller: AppBundle:Admin:antiguedad }
# ROUTING PARA INFO DE EMPLEADO
info_empleado:
    path: /info_empleado
    defaults: { _controller: AppBundle:Admin:infoempleado }
