docsoficiales_index:
    path:     /
    defaults: { _controller: "AppBundle:DocsOficiales:index" }
    methods:  GET

docsoficiales_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:DocsOficiales:show" }
    methods:  GET

docsoficiales_new:
    path:     /new
    defaults: { _controller: "AppBundle:DocsOficiales:new" }
    methods:  [GET, POST]

docsoficiales_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:DocsOficiales:edit" }
    methods:  [GET, POST]

docsoficiales_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:DocsOficiales:delete" }
    methods:  DELETE
