escolaridad_index:
    path:     /
    defaults: { _controller: "AppBundle:Escolaridad:index" }
    methods:  GET

escolaridad_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Escolaridad:show" }
    methods:  GET

escolaridad_new:
    path:     /new
    defaults: { _controller: "AppBundle:Escolaridad:new" }
    methods:  [GET, POST]

escolaridad_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Escolaridad:edit" }
    methods:  [GET, POST]

escolaridad_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Escolaridad:delete" }
    methods:  DELETE
