horario_index:
    path:     /
    defaults: { _controller: "AppBundle:Horario:index" }
    methods:  GET

horario_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Horario:show" }
    methods:  GET

horario_new:
    path:     /new
    defaults: { _controller: "AppBundle:Horario:new" }
    methods:  [GET, POST]

horario_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Horario:edit" }
    methods:  [GET, POST]

horario_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Horario:delete" }
    methods:  DELETE
