licencia_index:
    path:     /
    defaults: { _controller: "AppBundle:Licencia:index" }
    methods:  [GET, POST]

licencia_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Licencia:show" }
    methods:  GET

licencia_new:
    path:     /new
    defaults: { _controller: "AppBundle:Licencia:new" }
    methods:  [GET, POST]

licencia_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Licencia:edit" }
    methods:  [GET, POST]

licencia_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Licencia:delete" }
    methods:  DELETE
