subdireccion_index:
    path:     /
    defaults: { _controller: "AppBundle:Subdireccion:index" }
    methods:  GET

subdireccion_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Subdireccion:show" }
    methods:  GET

subdireccion_new:
    path:     /new
    defaults: { _controller: "AppBundle:Subdireccion:new" }
    methods:  [GET, POST]

subdireccion_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Subdireccion:edit" }
    methods:  [GET, POST]

subdireccion_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Subdireccion:delete" }
    methods:  DELETE
