tramite_index:
    path:     /
    defaults: { _controller: "AppBundle:Tramite:index" }
    methods:  GET

tramite_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Tramite:show" }
    methods:  GET

tramite_new:
    path:     /new
    defaults: { _controller: "AppBundle:Tramite:new" }
    methods:  [GET, POST]

tramite_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Tramite:edit" }
    methods:  [GET, POST]

tramite_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Tramite:delete" }
    methods:  DELETE
