AppBundle\Entity\Categoria:
    type: entity
    table: categoria
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        activo:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
        sueldo:
            type: float
            nullable: false
            precision: 10
            scale: 0
    lifecycleCallbacks: {  }
