AppBundle\Entity\DocsOficiales:
    type: entity
    table: docs_oficiales
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreDoc:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: nombre_doc
        activo:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
    lifecycleCallbacks: {  }
