AppBundle\Entity\Licencia:
    type: entity
    table: licencia
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreLic:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: nombre_lic
        activo:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
    lifecycleCallbacks: {  }
