AppBundle\Entity\Semestre:
    type: entity
    table: semestre
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        semestre:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        year:
            type: integer
            nullable: false
            options:
                unsigned: false
        activo:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
    lifecycleCallbacks: {  }
