AppBundle\Entity\Subdireccion:
    type: entity
    table: subdireccion
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreSubd:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: nombre_subd
        subdirector:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
