AppBundle\Entity\Tramite:
    type: entity
    table: tramite
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        activo:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
    lifecycleCallbacks: {  }
