<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHst1x8q\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHst1x8q/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHst1x8q.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHst1x8q\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHst1x8q\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Hst1x8q',
    'container.build_id' => '019c2ecb',
    'container.build_time' => 1545178848,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHst1x8q');
